const helperText = {
  singularName: "helper-text",
  pluginOptions: {
    i18n: {
      locale: "all",
    },
  },
  queryParams: {
    populate: {
      AddToCart: "*",
      CloseButton: "*",
      FooterPlaceholder: "*",
      NamePlaceholder: "*",
      EmailPlaceholder: "*",
      SignUpButton: "*",
      FindButton: "*",
      BreadcrumbHome: "*",
      ZoomProductImage: "*",
      AvailabilityText: "*",
      ShippingTime: "*",
      FreeShipping: "*",
      ShippingReturns: "*",
      ReadText: "*",
      Quantity: "*",
      BuyNow: "*",
      FrequentlyBought: "*",
      ChooseOption: "*",
      BuyProducts: "*",
      AndGet: "*",
      Discount: "*",
      NewItem: "*",
      ThisItem: "*",
      EmptyCart: "*",
      PurchaseType: "*",
      Price: "*",
      Total: "*",
      BillingCycle: "*",
      OneOffPurchase: "*",
      RegularPayment: "*",
      InvalidCoupon: "*",
      MyCart: "*",
      InStock: "*",
      OutOfStock: "*",
      More: "*",
      Less: "*",
      AskUs: "*",
      AskUsAnything: "*",
      Questions: "*",
      GoHome: "*",
      PageNotFound: "*",
    },
  },
}
module.exports = helperText
